const sagaActions = {
  INTIALIZED: 'INTIALIZED',
  LOG_OUT: 'LOG_OUT',
  SIGNUP_SAGA: 'SIGNUP_SAGA',

  GET_STOCKES: 'GET_STOCKES',
  GET_DISTRIBUTERS: 'GET_DISTRIBUTERS',
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  GET_VENDORS: 'GET_VENDORS',
  GET_EMPLOYEE: 'GET_EMPLOYEE',
  GET_INVOICE: 'GET_INVOICE',

  ADD_CUSTOMERS: 'ADD_CUSTOMERS',
  ADD_VENDORS: 'ADD_VENDORS',
  ADD_EMPLOYEE_LIST: 'ADD_EMPLOYEE_LIST',
  ADD_EMPLOYEE_TARGET: 'ADD_EMPLOYEE_TARGET',
  ADD_INVOICE: 'ADD_INVOICE',
  ADD_LEAD: 'ADD_LEAD',

  DELETE_CUSTOMERS: 'DELETE_CUSTOMERS',
  DELETE_VENDORS: 'DELETE_VENDORS',
  DELETE_EMPLOYEE_LIST: 'DELETE_EMPLOYEE_LIST',
  DELETE_EMPLOYEE_TARGET: 'DELETE_EMPLOYEE_TARGET',
  DELETE_INVOICE: 'DELETE_INVOICE',
  DELETE_LEAD: 'DELETE_LEAD',

  EDIT_CUSTOMERS: 'EDIT_CUSTOMERS',
  EDIT_VENDORS: 'EDIT_VENDORS',
  EDIT_EMPLOYEE_LIST: 'EDIT_EMPLOYEE_LIST',
  EDIT_EMPLOYEE_TARGET: 'EDIT_EMPLOYEE_TARGET',
  EDIT_INVOICE: 'EDIT_INVOICE',
  EDIT_LEAD: 'EDIT_LEAD',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UPLOAD_FILE: 'UPLOAD_FILE',

  ORDERDETAIL_SAGA: 'ORDERDETAIL_SAGA',
  ORDERTABLE_SAGA: 'ORDERTABLE_SAGA',
  LEADTABLE_SAGA: 'LEADTABLE_SAGA',
  DISCUSSIONTABLE_SAGA: 'DISCUSSIONTABLE_SAGA',
  VIEWINVOICEDETAIL_SAGA: 'VIEWINVOICEDETAIL_SAGA',
};

export default sagaActions;
